### ISSUE TITLE
Doesn't work

### ISSUE THREAD

**Issue by SergiOnGit** [bubjavier/react-native-dfp#8]
When i do import "import { RNBanner } from 'react-native-dfp';" i see this notice:

[ts] 'RNBanner' is declared but its value is never read.
[ts]
Could not find a declaration file for module 'react-native-dfp'. 'd:/projects/fortuna/node_modules/react-native-dfp/index.js' implicitly has an 'any' type.
  Try `npm install @types/react-native-dfp` if it exists or add a new declaration (.d.ts) file containing `declare module 'react-native-dfp';`
[ts]
Could not find a declaration file for module 'react-native-dfp'. 'd:/projects/fortuna/node_modules/react-native-dfp/index.js' implicitly has an 'any' type.
  Try `npm install @types/react-native-dfp` if it exists or add a new declaration (.d.ts) file containing `declare module 'react-native-dfp';`

**Comment by FullstackJack** [comment]
The problem is you're using TypeScript.

**Comment by SergiOnGit** [comment]
No i don't use TypeScript
